-- Tarif tablosu
CREATE TABLE IF NOT EXISTS recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  preparation_time INTEGER NOT NULL, -- Dakika cinsinden
  cooking_time INTEGER NOT NULL, -- Dakika cinsinden
  serving_size INTEGER NOT NULL,
  instructions TEXT,
  cost_per_serving NUMERIC(12, 2),
  category TEXT NOT NULL CHECK (category IN ('starter', 'main', 'dessert', 'beverage', 'side')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  image_url TEXT
);

-- Tarifin malzemeleri için bağlantı tablosu
CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity NUMERIC(12, 3) NOT NULL,
  unit TEXT NOT NULL
);

-- Menü tablosu
CREATE TABLE IF NOT EXISTS menus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  date DATE NOT NULL,
  description TEXT,
  status TEXT NOT NULL CHECK (status IN ('draft', 'planned', 'active', 'completed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  event_type TEXT,
  guest_count INTEGER,
  location TEXT,
  notes TEXT
);

-- Menü öğeleri için bağlantı tablosu
CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_id BIGINT NOT NULL REFERENCES menus(id) ON DELETE CASCADE,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL
);

-- Güvenlik politikaları
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipe_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;

-- recipes için politikalar
CREATE POLICY "Kullanıcılar kendi projelerindeki tarifleri görüntüleyebilir" ON recipes
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = recipes.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerine tarif ekleyebilir" ON recipes
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki tarifleri güncelleyebilir" ON recipes
  FOR UPDATE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = recipes.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki tarifleri silebilir" ON recipes
  FOR DELETE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = recipes.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- recipe_ingredients için politikalar
CREATE POLICY "Kullanıcılar kendi projelerindeki tarif malzemelerini görüntüleyebilir" ON recipe_ingredients
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM recipes
      WHERE recipes.id = recipe_ingredients.recipe_id
      AND (
        recipes.user_id = auth.uid() OR
        EXISTS (
          SELECT 1 FROM project_users
          WHERE project_users.project_id = recipes.project_id
          AND project_users.user_id = auth.uid()
        )
      )
    )
  );

CREATE POLICY "Kullanıcılar kendi tariflerine malzeme ekleyebilir" ON recipe_ingredients
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM recipes
      WHERE recipes.id = recipe_ingredients.recipe_id
      AND recipes.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi tariflerindeki malzemeleri güncelleyebilir" ON recipe_ingredients
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM recipes
      WHERE recipes.id = recipe_ingredients.recipe_id
      AND (
        recipes.user_id = auth.uid() OR
        EXISTS (
          SELECT 1 FROM project_users
          WHERE project_users.project_id = recipes.project_id
          AND project_users.user_id = auth.uid()
        )
      )
    )
  );

CREATE POLICY "Kullanıcılar kendi tariflerindeki malzemeleri silebilir" ON recipe_ingredients
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM recipes
      WHERE recipes.id = recipe_ingredients.recipe_id
      AND (
        recipes.user_id = auth.uid() OR
        EXISTS (
          SELECT 1 FROM project_users
          WHERE project_users.project_id = recipes.project_id
          AND project_users.user_id = auth.uid()
        )
      )
    )
  );

-- menus için politikalar
CREATE POLICY "Kullanıcılar kendi projelerindeki menüleri görüntüleyebilir" ON menus
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = menus.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerine menü ekleyebilir" ON menus
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki menüleri güncelleyebilir" ON menus
  FOR UPDATE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = menus.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki menüleri silebilir" ON menus
  FOR DELETE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = menus.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- menu_items için politikalar
CREATE POLICY "Kullanıcılar kendi projelerindeki menü öğelerini görüntüleyebilir" ON menu_items
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM menus
      WHERE menus.id = menu_items.menu_id
      AND (
        menus.user_id = auth.uid() OR
        EXISTS (
          SELECT 1 FROM project_users
          WHERE project_users.project_id = menus.project_id
          AND project_users.user_id = auth.uid()
        )
      )
    )
  );

CREATE POLICY "Kullanıcılar kendi menülerine öğe ekleyebilir" ON menu_items
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM menus
      WHERE menus.id = menu_items.menu_id
      AND menus.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi menülerindeki öğeleri güncelleyebilir" ON menu_items
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM menus
      WHERE menus.id = menu_items.menu_id
      AND (
        menus.user_id = auth.uid() OR
        EXISTS (
          SELECT 1 FROM project_users
          WHERE project_users.project_id = menus.project_id
          AND project_users.user_id = auth.uid()
        )
      )
    )
  );

CREATE POLICY "Kullanıcılar kendi menülerindeki öğeleri silebilir" ON menu_items
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM menus
      WHERE menus.id = menu_items.menu_id
      AND (
        menus.user_id = auth.uid() OR
        EXISTS (
          SELECT 1 FROM project_users
          WHERE project_users.project_id = menus.project_id
          AND project_users.user_id = auth.uid()
        )
      )
    )
  ); 