-- personnel tablosunu oluştur
CREATE TABLE IF NOT EXISTS personnel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  position TEXT NOT NULL,
  salary NUMERIC(12, 2) NOT NULL,
  hire_date DATE NOT NULL,
  birth_date DATE NOT NULL,
  location TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL
);

-- Personnel tablosu için RLS (Row Level Security) politikaları
ALTER TABLE personnel ENABLE ROW LEVEL SECURITY;

-- Projeye ait personeli görüntüleme politikası
CREATE POLICY "Kullanıcılar kendi projelerindeki personeli görüntüleyebilir" ON personnel
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = personnel.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- Projeye personel ekleme politikası
CREATE POLICY "Kullanıcılar kendi projelerine personel ekleyebilir" ON personnel
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
  );

-- Personel güncelleme politikası
CREATE POLICY "Kullanıcılar kendi projelerindeki personeli güncelleyebilir" ON personnel
  FOR UPDATE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = personnel.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- Personel silme politikası
CREATE POLICY "Kullanıcılar kendi projelerindeki personeli silebilir" ON personnel
  FOR DELETE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = personnel.project_id
      AND project_users.user_id = auth.uid()
    )
  ); 