-- Rapor yapılandırmaları için tablo
CREATE TABLE IF NOT EXISTS report_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('inventory', 'financial', 'personnel', 'customer', 'event', 'custom')),
  filters JSONB NOT NULL DEFAULT '[]',
  columns JSONB NOT NULL DEFAULT '[]',
  group_by JSONB,
  sort_by TEXT,
  sort_order TEXT CHECK (sort_order IN ('asc', 'desc')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  is_favorite BOOLEAN DEFAULT FALSE,
  schedule TEXT CHECK (schedule IN ('daily', 'weekly', 'monthly', 'quarterly')),
  recipients JSONB
);

-- İstatistik görünümleri
-- Stok ürünleri istatistikleri
CREATE OR REPLACE VIEW inventory_stats AS
  SELECT 
    project_id,
    COUNT(*) AS total_products,
    SUM(stock_quantity) AS total_stock,
    SUM(stock_quantity * price) AS total_value,
    AVG(price) AS avg_price,
    MAX(updated_at) AS last_updated
  FROM products
  GROUP BY project_id;

-- Stok hareketleri istatistikleri
CREATE OR REPLACE VIEW movement_stats AS
  SELECT
    project_id,
    date_trunc('month', date::date) AS month,
    type,
    COUNT(*) AS movement_count,
    SUM(quantity) AS total_quantity
  FROM stock_movements
  GROUP BY project_id, date_trunc('month', date::date), type;

-- Gider istatistikleri
CREATE OR REPLACE VIEW expense_stats AS
  SELECT
    project_id,
    date_trunc('month', date::date) AS month,
    COUNT(*) AS expense_count,
    SUM(amount) AS total_amount,
    AVG(amount) AS avg_amount
  FROM expenses
  GROUP BY project_id, date_trunc('month', date::date);

-- Personel istatistikleri (opsiyonel)
CREATE OR REPLACE VIEW personnel_stats AS
  SELECT
    project_id,
    COUNT(*) AS total_personnel,
    AVG(salary) AS avg_salary,
    SUM(salary) AS total_salary
  FROM personnel
  GROUP BY project_id;

-- Güvenlik politikaları
ALTER TABLE report_configs ENABLE ROW LEVEL SECURITY;

-- report_configs için politikalar
CREATE POLICY "Kullanıcılar kendi projelerindeki raporları görüntüleyebilir" ON report_configs
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = report_configs.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerine rapor ekleyebilir" ON report_configs
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki raporları güncelleyebilir" ON report_configs
  FOR UPDATE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = report_configs.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki raporları silebilir" ON report_configs
  FOR DELETE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = report_configs.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- İstatistik görünümleri için güvenlik
-- Ürünler tablosunda user_id sütunu olmadığı için hatalı politika kaldırıldı
-- CREATE POLICY "Kullanıcılar kendi projelerindeki stok istatistiklerini görüntüleyebilir" ON products
--   FOR SELECT USING (
--     auth.uid() = user_id OR
--     EXISTS (
--       SELECT 1 FROM project_users
--       WHERE project_users.project_id = products.project_id
--       AND project_users.user_id = auth.uid()
--     )
--   );

-- İstatistik görünümleri için RLS değil, görünüme erişim yetkileri ayarlama
GRANT SELECT ON inventory_stats TO authenticated;
GRANT SELECT ON movement_stats TO authenticated;
GRANT SELECT ON expense_stats TO authenticated;
GRANT SELECT ON personnel_stats TO authenticated; 