-- timesheet tablosunu oluştur
CREATE TABLE IF NOT EXISTS timesheet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personnel_id BIGINT NOT NULL REFERENCES personnel(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('present', 'absent', 'half_day', 'leave', 'holiday')),
  hours NUMERIC(4, 2),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL
);

-- Timesheet tablosu için unique constraint (bir personel, bir gün için bir kayıt)
ALTER TABLE timesheet ADD CONSTRAINT unique_personnel_date UNIQUE (personnel_id, date);

-- Timesheet tablosu için RLS (Row Level Security) politikaları
ALTER TABLE timesheet ENABLE ROW LEVEL SECURITY;

-- Projeye ait puantajları görüntüleme politikası
CREATE POLICY "Kullanıcılar kendi projelerindeki puantajları görüntüleyebilir" ON timesheet
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = timesheet.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- Projeye puantaj ekleme politikası
CREATE POLICY "Kullanıcılar kendi projelerine puantaj ekleyebilir" ON timesheet
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
  );

-- Puantaj güncelleme politikası
CREATE POLICY "Kullanıcılar kendi projelerindeki puantajları güncelleyebilir" ON timesheet
  FOR UPDATE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = timesheet.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- Puantaj silme politikası
CREATE POLICY "Kullanıcılar kendi projelerindeki puantajları silebilir" ON timesheet
  FOR DELETE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = timesheet.project_id
      AND project_users.user_id = auth.uid()
    )
  ); 