-- Müşteri tablosu
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  email TEXT,
  phone TEXT NOT NULL,
  address TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('individual', 'company', 'institution'))
);

-- Etkinlik tablosu
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  location TEXT NOT NULL,
  guest_count INTEGER NOT NULL,
  menu_id BIGINT REFERENCES menus(id) ON DELETE SET NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  total_price NUMERIC(12, 2) NOT NULL,
  advance_payment NUMERIC(12, 2),
  balance_due NUMERIC(12, 2),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID NOT NULL
);

-- Güvenlik politikaları
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- customers için politikalar
CREATE POLICY "Kullanıcılar kendi projelerindeki müşterileri görüntüleyebilir" ON customers
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = customers.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerine müşteri ekleyebilir" ON customers
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki müşterileri güncelleyebilir" ON customers
  FOR UPDATE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = customers.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki müşterileri silebilir" ON customers
  FOR DELETE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = customers.project_id
      AND project_users.user_id = auth.uid()
    )
  );

-- events için politikalar
CREATE POLICY "Kullanıcılar kendi projelerindeki etkinlikleri görüntüleyebilir" ON events
  FOR SELECT USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = events.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerine etkinlik ekleyebilir" ON events
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki etkinlikleri güncelleyebilir" ON events
  FOR UPDATE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = events.project_id
      AND project_users.user_id = auth.uid()
    )
  );

CREATE POLICY "Kullanıcılar kendi projelerindeki etkinlikleri silebilir" ON events
  FOR DELETE USING (
    auth.uid() = user_id OR
    EXISTS (
      SELECT 1 FROM project_users
      WHERE project_users.project_id = events.project_id
      AND project_users.user_id = auth.uid()
    )
  ); 